language: python
python:
- '3.6'
install:
- pip install -U pip wheel
- pip install -r requirements.txt
script:
- echo "skip"
deploy:
  skip_existing: true
  provider: pypi
  user: __token__
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJGFjODliOWQ2LTc1NWYtNDBmYy1hYmRiLTMwMGE0NTk2NWQ2ZQACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgBXoIa4wOERMdE87NOLoCuZ7lLYb77uF2BgkOln43Ze0
  distributions: sdist bdist_wheel
  repo: alibaba/web-editor
  on:
    tags: true
